=== PabloPereiraHospido/LMSX2425/UD3/Teoria/Clinica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

    <xs:element name="clinica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mascotas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mascota" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element
                                            name="especie"
                                            type="xs:string" />
                                        <xs:element
                                            name="raza"
                                            type="xs:string" />
                                        <xs:element
                                            name="edad"
                                            type="xs:integer" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PabloPereiraHospido/LMSX2425/UD3/Teoria/Clinica.xml
<?xml version="1.0" encoding="UTF-8"?>

<clinica
    xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.w3schools.com/xml ./Clinica.xsd"
>
    <mascotas>
        <mascota cod="01">
            <especie>Perro</especie>
            <raza>Golden Retriever</raza>
            <edad>5</edad>
        </mascota>
        <mascota cod="02">
            <especie>Gato</especie>
            <raza>Siames</raza>
            <edad>3</edad>
        </mascota>
        <mascota cod="03">
            <especie>Conejo</especie>
            <raza>Holland Lops</raza>
            <edad>2</edad>
        </mascota>
    </mascotas>
</clinica>
